// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microsoft.Health.Fhir.Facade.SqlServer.EF
{
    [Index(nameof(ResourceSurrogateId), Name = "IX_Resource_ResourceSurrogateId", IsUnique = true)]
    [Index(nameof(ResourceTypeId), nameof(ResourceId), nameof(Version), Name = "IX_Resource_ResourceTypeId_ResourceId_Version", IsUnique = true)]
    public partial class Resource
    {
        [Key]
        public short ResourceTypeId { get; set; }
        [Required]
        [StringLength(64)]
        [Unicode(false)]
        public string ResourceId { get; set; }
        public int Version { get; set; }
        public bool IsHistory { get; set; }
        [Key]
        public long ResourceSurrogateId { get; set; }
        public bool IsDeleted { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string RequestMethod { get; set; }
        [Required]
        public byte[] RawResource { get; set; }
        public bool IsRawResourceMetaSet { get; set; }
        [StringLength(64)]
        [Unicode(false)]
        public string SearchParamHash { get; set; }
    }
}