// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microsoft.Health.Fhir.Facade.SqlServer.EF
{
    [Index(nameof(ResourceTypeId), Name = "UQ_ResourceType_ResourceTypeId", IsUnique = true)]
    public partial class ResourceType
    {
        public short ResourceTypeId { get; set; }
        [Key]
        [StringLength(50)]
        public string Name { get; set; }
    }
}