// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microsoft.Health.Fhir.Facade.SqlServer.EF
{
    [Index(nameof(SearchParamId), Name = "UQ_SearchParam_SearchParamId", IsUnique = true)]
    public partial class SearchParam
    {
        public short SearchParamId { get; set; }
        [Key]
        [StringLength(128)]
        [Unicode(false)]
        public string Uri { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Status { get; set; }
        public DateTimeOffset? LastUpdated { get; set; }
        public bool? IsPartiallySupported { get; set; }
    }
}