// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microsoft.Health.Fhir.Facade.SqlServer.EF
{
    [Index(nameof(SystemId), Name = "UQ_System_SystemId", IsUnique = true)]
    public partial class System
    {
        public int SystemId { get; set; }
        [Key]
        [StringLength(256)]
        public string Value { get; set; }
    }
}