// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microsoft.Health.Fhir.Facade.SqlServer.EF
{
    [Keyless]
    public partial class TokenSearchParam
    {
        public short ResourceTypeId { get; set; }
        public long ResourceSurrogateId { get; set; }
        public short SearchParamId { get; set; }
        public int? SystemId { get; set; }
        [Required]
        [StringLength(128)]
        [Unicode(false)]
        public string Code { get; set; }
        public bool IsHistory { get; set; }
    }
}